# Utiliser l'image officielle Node.js
FROM node:latest

# Créer le répertoire de travail de l'application
WORKDIR /app

# Copier les fichiers de l'application dans le conteneur
COPY package.json .
COPY package-lock.json .
COPY index.js .

# Installer les dépendances
RUN npm install

# Exposer le port sur lequel l'application s'exécute
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["node", "index.js"]
